In [2]:
import requests
import pandas as pd
import json

def busca_residente(resident_url):
    #resident_url = "https://rickandmortyapi.com/api/character/38"
    resident = requests.get(resident_url).json()
    return resident['name'] + "," + resident['species']

URL="https://rickandmortyapi.com/api/location"

ARCHIVO='locations.csv'
fichero = open(ARCHIVO, 'w')
fichero.write('id, name, type, dimension, resident1-name, resident1-species\n')
while(URL != None):
    locations_quest= requests.get(URL)
    for location in (locations_quest.json()['results']):
        aux_residente=''
        if len(location['residents']) > 0:
            aux_residente=busca_residente(location['residents'][0])
        aux_residente = location['id'] + "," + location['name'] + "," + location['type'] + "," + location['dimension'] + "," + aux_residente + '\n'
        fichero.write(aux_residente)
    URL=locations_quest.json()['info']['next']
    print("-------------------------------------")
    print(URL)
    print("-------------------------------------")

fichero.close()

-------------------------------------
https://rickandmortyapi.com/api/location?page=2
-------------------------------------
-------------------------------------
https://rickandmortyapi.com/api/location?page=3
-------------------------------------
-------------------------------------
https://rickandmortyapi.com/api/location?page=4
-------------------------------------
-------------------------------------
https://rickandmortyapi.com/api/location?page=5
-------------------------------------
-------------------------------------
https://rickandmortyapi.com/api/location?page=6
-------------------------------------
-------------------------------------
https://rickandmortyapi.com/api/location?page=7
-------------------------------------
-------------------------------------
None
-------------------------------------

In [10]:
df = pd.read_csv(ARCHIVO)
df.to_json('locations.json')
df.to_parquet('locations.parquet')
df.to_csv('locations2.csv')

In [11]:
df[df[' type'] == 'Planet']

,id,name,type,dimension,resident1-name,resident1-species
0,1,Earth (C-137),Planet,Dimension C-137,Beth Smith,Human
3,4,Worldender's lair,Planet,unknown,Alan Rails,Human
7,8,Post-Apocalyptic Earth,Planet,Post-Apocalyptic Dimension,Armothy,unknown
8,9,Purge Planet,Planet,Replacement Dimension,Arthricia,Alien
9,10,Venzenulon 7,Planet,unknown,Beebo,Alien
...,...,...,...,...,...,...
111,112,Morglutz,Planet,Replacement Dimension,Morglutzian,Alien
112,113,Ferkus 9,Planet,Replacement Dimension,Daphne,Alien
121,122,Avian Planet,Planet,Replacement Dimension,Alien Crow,Alien
123,124,Slartivart,Planet,Replacement Dimension,Slartivartian,Alien
124,125,Rick and Two Crows Planet,Planet,Replacement Dimension,Pussifer,Animal

In [13]:
df.groupby(['dimension']).size()

KeyError: 'dimension'

In [ ]:
df[df['id']<100]

In [ ]:
df[df['planet'].str.startswith('Earth')]